#!/system/bin/sh

bb=/sbin/bb/busybox

# wait for systemui to be up
until [ $($bb pgrep com.android.systemui) ] ; do
  $bb sleep 1
done

$bb sleep 5

# decrease max. realtime cpu runtime of background apps
$bb echo 91 > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
$bb echo 400000 > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us

# change niceness of systemui
$bb renice -10 $($bb pgrep com.android.systemui)

# move systemui to the parent task group
$bb echo $($bb pgrep com.android.systemui) > /dev/cpuctl/tasks

# move uksm daemon to bg_non_interactive task group
$bb echo $($bb pgrep uksmd) > /dev/cpuctl/apps/bg_non_interactive/tasks

# set cgroup_timer_slack for bg_non_interactive tasks
$bb echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns
